spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      spring.json.trusted.packages: com.example.models.*
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.example.kafka101.utils.AESDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  com.example.kafka101.utils.AESSerializer

server:
  port: 8888


salah:
  kafka:
    topics:
      topic1:
        topic: topic1
        secret: sercret1
        salt: salt1
      topic2:
        topic: topic2
        secret: sercret2
        salt: salt2
      topic3:
        topic: topic3
        secret: secret3
        salt: salt3
